pipeline {
    agent any

    tools {
        maven 'M3'
    }

    parameters {
        choice(
            name: 'ENVIRONMENT',
            choices: ['dev', 'qa', 'prod'],
            description: 'Select environment to build/deploy'
        )
    }

    environment {
        JAVA_HOME = "/usr/lib/jvm/java-21-openjdk"
        PATH = "${JAVA_HOME}/bin:/usr/share/maven/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Checking out code from GitHub"
                git branch: 'master', url: 'https://github.com/jaabhilash13/simple-java-maven-app.git'
            }
        }

        stage('Build') {
            steps {
                echo "Building for ${params.ENVIRONMENT} environment"
                sh """
                java -version
                mvn clean package -Denv=${params.ENVIRONMENT}
                """
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying to ${params.ENVIRONMENT} environment"
                sh "echo 'Deploying to ${params.ENVIRONMENT}'"
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully for ${params.ENVIRONMENT}"
        }
        failure {
            echo "Pipeline failed for ${params.ENVIRONMENT}"
        }
    }
}
