pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
        steps {
        echo "Building for ${params.ENVIRONMENT} environment"
        sh """
        export PATH=/usr/share/maven/bin:\$PATH
        java -version
        mvn clean package -Denv=${params.ENVIRONMENT}
        """
    }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
